name: main CI
on: push # Триггер для запуска workflow при push в репозиторий
jobs:
  build:
    runs-on: ubuntu-latest # Окружение для выполнения задачи
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Действие для клонирования репозитория
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Установка Node.js
      - name: Install dependencies
        run: make install # Установка зависимостей
      - name: Run linter
        run: make lint # Запуск линтера
      - name: Run tests
        run: make test # Запуск тестов

      - name: Run Code Climate action
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CODECLIMATE_TOKEN: ${{ secrets.CODECLIMATE_TOKEN_2 }}
        with:
          coverageCommand: make test-coverage
          debug: true
#
# Ключевое слово uses в GitHub Actions позволяет подключать готовые действия для выполнения задач, что значительно упрощает создание и поддержку рабочих процессов
# Ключевое слово run в GitHub Actions позволяет выполнять пользовательские команды и скрипты, что делает рабочие процессы гибкими и адаптируемыми под нужды вашего проекта

# Разница между uses и run
# uses:
# Подключает готовые действия (actions) из репозиториев GitHub.
# Используется для повторного использования кода (например, клонирование репозитория, настройка Node.js).
# Пример: uses: actions/checkout@v4.
# run:
# Выполняет произвольные команды или скрипты.
# Используется для задач, специфичных для вашего проекта (например, установка зависимостей, запуск тестов).
# Пример: run: npm install.
